locale: en # Supports locales: en / ru
update:
  check: true # Send notifications in console if it detects new version
  auto: false # Plugin auto-update. Don't enable on Windows servers!
portals:
  end: true # Is end portals enabled
  nether: true # Is nether portals enabled
destinations: # Change destination worlds (Nether - world_nether, End - world_the_end, Overworld - world)
  end:
    enabled: false # Is change destination world enabled
    world: world_nether # Destination world
    coords: [ 0, 0, 0, 0, 0 ] # Coordinates (X, Y, Z, Yaw, Pitch)
  nether:
    enabled: false # Is change destination world enabled
    world: world_the_end # Destination world
    coords: [ 0, 0, 0, 0, 0 ] # Coordinates (X, Y, Z, Yaw, Pitch)
works:
  players: true # Is plugin works on players
  entities: true # Is plugin works on other entities